Fixed a race condition discovered by nahi-san in Stapler JRuby HAML support.
The problem is that the synchronized block on the getJellyProperties() method wasn't helping in case when multiple instances of XMLParsers are executed concurrently by different threads and they all call into getJellyProperties() methods about the same time. The 2nd thread that comes in can end up using the partially constructed Properties.

Since this method is protected, it can be potentially subtyped by existing code elsewhere. My change preserves the signature but still correctly loads the default jelly.properties fully in a concurrent safe manner.

The full stack trace below:
---------------

Jun 24, 2011 1:30:48 PM org.apache.commons.jelly.parser.XMLParser createSAXException
WARNING: Underlying exception: java.lang.ClassNotFoundException: core
Jun 24, 2011 1:30:48 PM org.apache.commons.jelly.parser.XMLParser createSAXException
WARNING: Underlying exception: java.lang.ClassNotFoundException: core
Jun 24, 2011 1:30:51 PM org.apache.commons.jelly.parser.XMLParser createTag
WARNING: Could not create taglib or URI: jelly:core tag name: jelly
org.apache.commons.jelly.util.SAXParseException: Error at (1, 31) of file:/home/nahi/git/stapler/jruby/target/test-classes/lib/form/abc.jelly : Could not load class: core so taglib instantiation failed
        at org.apache.commons.jelly.parser.XMLParser.createSAXException(XMLParser.java:1241)
        at org.apache.commons.jelly.parser.XMLParser.createTag(XMLParser.java:1025)
        at org.apache.commons.jelly.parser.XMLParser.startElement(XMLParser.java:638)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.commons.jelly.parser.XMLParser.parse(XMLParser.java:350)
        at org.apache.commons.jelly.JellyContext.compileScript(JellyContext.java:525)
        at org.kohsuke.stapler.jelly.CustomTagLibrary.loadJellyScript(CustomTagLibrary.java:149)
        at org.kohsuke.stapler.jelly.CustomTagLibrary.load(CustomTagLibrary.java:129)
        at org.kohsuke.stapler.jelly.CustomTagLibrary.load(CustomTagLibrary.java:118)
        at org.kohsuke.stapler.jelly.CustomTagLibrary.createTagScript(CustomTagLibrary.java:77)
        at org.kohsuke.stapler.jelly.jruby.JRubyJellyScript.createTagScript(JRubyJellyScript.java:72)
        at org.kohsuke.stapler.jelly.jruby.JRubyJellyScript.invokeTaglib(JRubyJellyScript.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:491)
        at org.jruby.javasupport.JavaMethod.tryProxyInvocation(JavaMethod.java:689)
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:353)
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:42)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:69)
        at org.jruby.ast.CallManyArgsNode.interpret(CallManyArgsNode.java:59)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:120)
        at org.jruby.javasupport.util.RuntimeHelpers$MethodMissingMethod.call(RuntimeHelpers.java:497)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:209)
        at org.jruby.runtime.callsite.CachingCallSite.callMethodMissing(CachingCallSite.java:365)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:289)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:148)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:157)
        at org.jruby.ast.CallOneArgBlockNode.interpret(CallOneArgBlockNode.java:60)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.RootNode.interpret(RootNode.java:129)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_EVAL(ASTInterpreter.java:95)
        at org.jruby.evaluator.ASTInterpreter.evalWithBinding(ASTInterpreter.java:160)
        at org.jruby.RubyKernel.evalCommon(RubyKernel.java:1135)
        at org.jruby.RubyKernel.eval(RubyKernel.java:1088)
        at org.jruby.RubyKernel$s$0$3$eval.call(RubyKernel$s$0$3$eval.gen:65535)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:179)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:69)
        at org.jruby.ast.FCallManyArgsNode.interpret(FCallManyArgsNode.java:60)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:190)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:137)
        at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:111)

        at org.jruby.runtime.InterpretedBlock.evalBlockBody(InterpretedBlock.java:374)
        at org.jruby.runtime.InterpretedBlock.yield(InterpretedBlock.java:347)
        at org.jruby.runtime.InterpretedBlock.yield(InterpretedBlock.java:304)
        at org.jruby.runtime.Block.yield(Block.java:130)
        at org.jruby.ast.YieldNode.interpret(YieldNode.java:112)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:169)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:112)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:123)
        at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.RescueNode.executeBody(RescueNode.java:216)
        at org.jruby.ast.RescueNode.interpretWithJavaExceptions(RescueNode.java:120)
        at org.jruby.ast.RescueNode.interpret(RescueNode.java:110)
        at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:120)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:134)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$2.invoke(JavaProxyConstructor.java:225)
        at org.jruby.proxy.org.kohsuke.stapler.jelly.jruby.JRubyJellyScript$Proxy0.run(Unknown Source)
        at org.kohsuke.stapler.jelly.jruby.JRubyJellyHamlScriptTest$EvaluatorThread.run(JRubyJellyHamlScriptTest.java:78)
Caused by: java.lang.ClassNotFoundException: core
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at org.apache.commons.jelly.parser.XMLParser.createTag(XMLParser.java:1020)
        ... 83 more
Jun 24, 2011 1:30:51 PM org.apache.commons.jelly.parser.XMLParser createSAXException
WARNING: Underlying exception: org.apache.commons.jelly.util.SAXParseException: Error at (1, 31) of file:/home/nahi/git/stapler/jruby/target/test-classes/lib/form/abc.jelly : Could not load class: core so taglib instantiation failed
Jun 24, 2011 1:30:51 PM org.apache.commons.jelly.parser.XMLParser createTag
WARNING: Could not create taglib or URI: jelly:core tag name: jelly
org.apache.commons.jelly.util.SAXParseException: Error at (1, 31) of file:/home/nahi/git/stapler/jruby/target/test-classes/lib/form/abc.jelly : Could not load class: core so taglib instantiation failed
        at org.apache.commons.jelly.parser.XMLParser.createSAXException(XMLParser.java:1241)
        at org.apache.commons.jelly.parser.XMLParser.createTag(XMLParser.java:1025)
        at org.apache.commons.jelly.parser.XMLParser.startElement(XMLParser.java:638)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.commons.jelly.parser.XMLParser.parse(XMLParser.java:350)
        at org.apache.commons.jelly.JellyContext.compileScript(JellyContext.java:525)
        at org.kohsuke.stapler.jelly.CustomTagLibrary.loadJellyScript(CustomTagLibrary.java:149)
        at org.kohsuke.stapler.jelly.CustomTagLibrary.load(CustomTagLibrary.java:129)
        at org.kohsuke.stapler.jelly.CustomTagLibrary.load(CustomTagLibrary.java:118)
        at org.kohsuke.stapler.jelly.CustomTagLibrary.createTagScript(CustomTagLibrary.java:77)
        at org.kohsuke.stapler.jelly.jruby.JRubyJellyScript.createTagScript(JRubyJellyScript.java:72)
        at org.kohsuke.stapler.jelly.jruby.JRubyJellyScript.invokeTaglib(JRubyJellyScript.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:491)
        at org.jruby.javasupport.JavaMethod.tryProxyInvocation(JavaMethod.java:689)
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:353)

        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:42)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:69)
        at org.jruby.ast.CallManyArgsNode.interpret(CallManyArgsNode.java:59)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:120)
        at org.jruby.javasupport.util.RuntimeHelpers$MethodMissingMethod.call(RuntimeHelpers.java:497)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:209)
        at org.jruby.runtime.callsite.CachingCallSite.callMethodMissing(CachingCallSite.java:365)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:289)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:148)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:157)
        at org.jruby.ast.CallOneArgBlockNode.interpret(CallOneArgBlockNode.java:60)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.RootNode.interpret(RootNode.java:129)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_EVAL(ASTInterpreter.java:95)
        at org.jruby.evaluator.ASTInterpreter.evalWithBinding(ASTInterpreter.java:160)
        at org.jruby.RubyKernel.evalCommon(RubyKernel.java:1135)
        at org.jruby.RubyKernel.eval(RubyKernel.java:1088)
        at org.jruby.RubyKernel$s$0$3$eval.call(RubyKernel$s$0$3$eval.gen:65535)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:179)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:69)
        at org.jruby.ast.FCallManyArgsNode.interpret(FCallManyArgsNode.java:60)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:190)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:137)
        at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:111)
        at org.jruby.runtime.InterpretedBlock.evalBlockBody(InterpretedBlock.java:374)
        at org.jruby.runtime.InterpretedBlock.yield(InterpretedBlock.java:347)
        at org.jruby.runtime.InterpretedBlock.yield(InterpretedBlock.java:304)
        at org.jruby.runtime.Block.yield(Block.java:130)
        at org.jruby.ast.YieldNode.interpret(YieldNode.java:112)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:169)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:112)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:123)
        at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.RescueNode.executeBody(RescueNode.java:216)
        at org.jruby.ast.RescueNode.interpretWithJavaExceptions(RescueNode.java:120)
        at org.jruby.ast.RescueNode.interpret(RescueNode.java:110)
        at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:120)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:134)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$2.invoke(JavaProxyConstructor.java:225)
        at org.jruby.proxy.org.kohsuke.stapler.jelly.jruby.JRubyJellyScript$Proxy0.run(Unknown Source)
        at org.kohsuke.stapler.jelly.jruby.JRubyJellyHamlScriptTest$EvaluatorThread.run(JRubyJellyHamlScriptTest.java:78)
Caused by: java.lang.ClassNotFoundException: core
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at org.apache.commons.jelly.parser.XMLParser.createTag(XMLParser.java:1020)
        ... 83 more
Jun 24, 2011 1:30:51 PM org.apache.commons.jelly.parser.XMLParser createSAXException

WARNING: Underlying exception: org.apache.commons.jelly.util.SAXParseException: Error at (1, 31) of file:/home/nahi/git/stapler/jruby/target/test-classes/lib/form/abc.jelly : Could not load class: core so taglib instantiation failed